config:
  gcp:project: mealio-483914
  gcp:region: us-east4
  mealio:cloudflareAccountId: "6dfc3725a77bb65a15378d6daa420312"
  mealio:r2PublicUrl: "https://pub-a6ac381f54d7453392feeeac89f6dc8b.r2.dev"
  # Set via: pulumi config set mealio:neonProjectId <value>
  # mealio:neonProjectId:
  # No secrets needed — prod values already live in GCP Secret Manager

  mealio:neonProjectId: steep-band-82375288
