services:
  postgres:
    image: postgres:18-alpine
    container_name: mealio-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mealio_dev
    volumes:
      - mealio_pgdata:/var/lib/postgresql/data

volumes:
  mealio_pgdata:
